baseURL = "https://aissam.me/"
languageCode = "en-us"
title = "Aissam Belhachmi"
theme = "aissam"
enableEmoji = true

[params]
  description = "Software Engineer"
  github = "https://github.com/Edmeral"
  email = "edmeral.aissam@gmail.com"

[markup]
  [markup.highlight]
    lineNos = false
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
